apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  selector:
    app: blue-app  # Default to blue, will be updated by pipeline
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
